In [2]:
!pip install numpy 
import numpy as np

print(np.__version__) # to check the version


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


2.4.1


In [ ]:
import numpy as np

#   1 Dimension array 
a = np.array([1,2,4,6]) #index : 0 1 2 3 4 5 

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 4 6]


In [30]:
# 2 Dimension Arrray 
a = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [1, 2, 3, 4]])

# print(len(a))

for i in a:
    print(i)


[1 3 5 7]
[2 4 6 8]
[1 2 3 4]


In [ ]:
#floating type array and type casting (.astype(np.intr))

array = np.array([1.0, 3.7, 3.45, 6.9], dtype=np.float64)
print(array)

conversion_array = array.astype(np.int16)

print(conversion_array)



[1.   3.7  3.45 6.9 ]
[1 3 3 6]


In [ ]:
#Array creation 
a_array = array([2, 4, 6, 8])
b_array = array([1, 3, 5, 7])

new_arry = a_array + b_array

print(new_arry)